name: reale
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  argon_buttons_flutter: ^1.1.0
  flutter_signin_button: ^2.0.0
  google_fonts: ^3.0.0
  pin_code_text_field: null
  http: ^0.13.4
  google_maps_flutter: ^2.1.8
  country_code_picker: ^2.0.2
  scaffold_tab_bar: 0.0.2
  geolocator: ^9.0.0
  dash_chat: ^1.1.16
  image_picker: ^0.8.5+3
  flutter_dropdown: ^1.0.0+hotfix.1
  url_launcher: ^6.0.5
  rflutter_alert: ^2.0.4
  grouped_buttons: ^1.0.4
  enhanced_drop_down: ^0.1.2
  dropdown_search: null
  simple_database: ^2.0.1
  flutter_range_slider: ^1.5.0
  carousel_images: ^1.1.2
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.5
  flutter_ringtone_player: ^3.1.1
  modal_progress_hud: ^0.1.3
  firebase_storage: ^10.2.18
  firebase_dynamic_links: ^4.2.6
  firebase_messaging: ^13.0.0
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  fluttertoast: ^8.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  group_radio_button: ^1.2.0



dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/images/pm.png"
  ios: true
  android: "ic_launcher"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/pm.png
#     - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
